# NumPy Recreation

## Python lists vs NumPy arrays
No vectorization with lists!

In [12]:
import numpy as np
data = [10, 19, -5, 8, 7, -4]
array = np.array(data)

### Add 5 to each element in the list

In [13]:
[d + 5 for d in data]

[15, 24, 0, 13, 12, 1]

In [14]:
array + 5

array([15, 24,  0, 13, 12,  1])

## Sum data

In [16]:
sum(data)

35

In [17]:
array.sum()

35

## Find the max

In [18]:
max(data)

19

In [19]:
array.max()

19

## Logical Comparisons

In [27]:
[d > 3 for d in data]

[True, True, False, True, True, False]

In [28]:
array > 3

array([ True,  True, False,  True,  True, False], dtype=bool)

## Select items

In [29]:
data[3]

8

In [30]:
array[3]

8

In [31]:
data[:3]

[10, 19, -5]

In [32]:
array[:3]

array([10, 19, -5])

In [35]:
items = [1, 3, 4]

In [36]:
[data[i] for i in items]

[19, 8, 7]

In [37]:
array[items]

array([19,  8,  7])

## Statistics

In [38]:
sum(data) / len(data)

5.833333333333333

In [39]:
array.mean()

5.833333333333333

In [41]:
import statistics

In [44]:
statistics.mean(data)

5.833333333333333

In [45]:
def mean(data):
    return sum(data) / len(data)

In [46]:
def var(data):
    m = mean(data)
    return sum([(d - m) ** 2 for d in data]) / len(data)

In [47]:
var(data)

68.47222222222221

In [48]:
statistics.variance(data)

82.16666666666666

In [50]:
array.var()

68.472222222222214

## Other array methods

In [53]:
# argmax
def argmax(data):
    cur_max = data[0]
    cur_pos = 0
    for i, d in enumerate(data):
        if d > cur_max:
            cur_max = d
            cur_pos = i
    return cur_pos

In [54]:
argmax(data)

1

In [59]:
array.argmax()

1

In [60]:
# cumsum
def cumsum(data):
    data2 = []
    total = 0
    for d in data:
        total += d
        data2.append(total)
    return data2

In [61]:
cumsum(data)

[10, 29, 24, 32, 39, 35]

In [62]:
array.cumsum()

array([10, 29, 24, 32, 39, 35])

In [66]:
# dot product
data2 = [9, 0, 3, -8, 12, 15]
array2 = np.array(data2)

In [74]:
sum([d1 * d2 for d1, d2 in zip(data, data2)])

35

In [73]:
array.dot(array2)

35

## Speed difference between arrays and lists

In [86]:
n = 100000
np.random.seed(1234)

array = np.random.rand(n)
data = array.tolist()

In [87]:
data[:5]

[0.1915194503788923,
 0.6221087710398319,
 0.4377277390071145,
 0.7853585837137692,
 0.7799758081188035]

In [88]:
array[:5]

array([ 0.19151945,  0.62210877,  0.43772774,  0.78535858,  0.77997581])

In [89]:
%timeit [d + 5 for d in data]

6.88 ms ± 148 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [90]:
%timeit array + 5

55 µs ± 1.06 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [92]:
%timeit sum(data)

558 µs ± 18 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [93]:
%timeit array.sum()

42.4 µs ± 1.32 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


# Object Oriented Programming in Python
* Everything is an object
* All objects have attributes and methods
* Attributes are descriptions - nouns. References to other object
* Methods are actions - verbs. Must be called with parentheses
* People and Car classes
* Classes are templates or blue prints that give you instructions on how to create objects
* Differences between classes and objects
* Define a class, instantiate it to create an object
* Objects are also called instances of the class

# Creating a class
* Create a class with one instance attribute, **`data`**
* Use **`__init__`** to initialize the object

# Check a few functions and operators to see what happens
* **`len, max, min, +, etc...`** 

# Create our own add method
* Does it work with plus sign?

# Create our own len method
* Does it work with len function?

# Special methods
* They are key to having your object work with operators and built-in functions
* They are formally defined in the Python [data model](https://docs.python.org/3/reference/datamodel.html#special-method-names)
* We will first [emulate numeric types](https://docs.python.org/3/reference/datamodel.html#emulating-numeric-types)
* Then **`__len__`**
* Then the [rich comparison (or logical) operators](https://docs.python.org/3/reference/datamodel.html#object.__lt__)
* Then the [container types](https://docs.python.org/3/reference/datamodel.html#emulating-container-types)